### ISSUE TITLE
Could not find generator thredded:install.

### ISSUE THREAD

**Issue by maximchick** [jayroh/thredded#57]
Hi, 

I'm trying to install thredded on rails 4.0.1

...
Using unf 0.1.4
Using thredded 0.0.13
Using turbolinks 2.5.3
Using uglifier 2.7.0
Your bundle is complete!

then accordingly to installation instruction I run:

$ rails generate thredded:install

and get following error:

Could not find generator thredded:install.

**Comment by jayroh** [comment]
Hey @maximchick! I think this might be because of the version that's up as a gem right now versus what's in master.  If you change your Gemfile to look like so:

```ruby
gem 'thredded', github: 'jayroh/thredded'
```

and `bundle update thredded` -- you should be able to find the generator! :boom:  :+1: 

In the meantime I *really* should put something in the README letting people know the instructions are relevant to master. Anyways - If there are any additional issues please don't hesitate to let me know :)

**Comment by jayroh** [comment]
@maximchick let me know if this still posed any more problems. If need be I could open this back up.
